# permissions for end users to edit catalogserviceclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogserviceclaim-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - catalogserviceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - catalogserviceclaims/status
  verbs:
  - get
