# permissions for end users to view catalogserviceclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogserviceclaim-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - catalogserviceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - catalogserviceclaims/status
  verbs:
  - get
