# permissions for end users to view clustertemplateclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplateclaim-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims/status
  verbs:
  - get
