# permissions for end users to edit clustertemplateclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertemplateclaim-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims/status
  verbs:
  - get
