
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - clustertemplateclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tmax.io
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - clustertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tmax.io
  resources:
  - templateinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - templateinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tmax.io
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
