# permissions for end users to edit templateinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templateinstance-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - templateinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - templateinstances/status
  verbs:
  - get
