apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: cluster-nginx-template-instance
  namespace: default
spec:
  clustertemplate:
    metadata:
      name: cluster-nginx-template
    parameters:
    - name: NAME
      value: nginx1
    - name: IMAGE
      value: nginx:1
